apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "k3s-server.fullname" . }}
  labels:
    {{- include "k3s-server.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  routes:
    - match: HostSNI(`{{ $.Values.domain }}`)
      services:
        - name: {{ include "k3s-server.fullname" $ }}
          port: {{ $.Values.service.port }}
  tls:
    passthrough: true