apiVersion: v1
kind: ConfigMap
metadata:
  name: "headscale-{{ include "k3s-server.fullname" . }}"
  labels:
    {{- include "k3s-server.labels" . | nindent 4 }}
data:
  config.yaml: |
    server_url: "http://headscale.{{ $.Values.domain }}"
    listen_addr: 0.0.0.0:8080
    metrics_listen_addr: 0.0.0.0:9090
    grpc_listen_addr: 0.0.0.0:50443
    grpc_allow_insecure: true
    noise:
      private_key_path: /etc/headscale_secret/noise_private.key
    prefixes:
      v4: 100.64.0.0/10
      allocation: sequential
    derp:
      server:
        enabled: false
      urls:
        - https://controlplane.tailscale.com/derpmap/default
      paths: []
      auto_update_enabled: true
      update_frequency: 24h
    disable_check_updates: true
    ephemeral_node_inactivity_timeout: 30m
    database:
      type: postgres
      debug: false
      gorm:
        prepare_stmt: true
        parameterized_queries: true
        skip_err_record_not_found: true
        slow_threshold: 1000
      {{ $.Values.hs.database.type }}:
        host: "{{ $.Values.hs.database.hostname }}"
        port: "{{ $.Values.hs.database.port }}"
        name: "{{ include "k3s-server.sanitizeNameHeadscale" . }}"
        user: "{{ $.Values.hs.database.username }}"
        pass: "{{ $.Values.hs.database.password }}"
        max_open_conns: 10
        max_idle_conns: 10
        conn_max_idle_time_secs: 3600
        ssl: false
    log:
      format: text
      level: info
    dns:
      magic_dns: true
      base_domain: gotizond
      nameservers:
        global:
          - 10.43.0.10 #TODO local k8s
          - 1.1.1.1
          - 1.0.0.1
          - 2606:4700:4700::1111
          - 2606:4700:4700::1001
        split:
          {}
      search_domains: []
      extra_records: []
    unix_socket: /var/run/headscale/headscale.sock
    unix_socket_permission: "0770"
    logtail:
      enabled: false
    randomize_client_port: false