apiVersion: v1
kind: ServiceAccount
metadata:
  name: "headscale-{{ include "k3s-server.fullname" . }}"
  labels:
    {{- include "k3s-server.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k3s-server.fullname" . }}-secret-manager
  labels:
    {{- include "k3s-server.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "k3s-server.fullname" . }}-secret-manager-binding
  labels:
    {{- include "k3s-server.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "k3s-server.fullname" . }}-secret-manager
subjects:
  - kind: ServiceAccount
    name: "headscale-{{ include "k3s-server.fullname" . }}"
    namespace: {{ .Release.Namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "k3s-server.fullname" . }}-post-start-job"
  labels:
    {{- include "k3s-server.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  ttlSecondsAfterFinished: 0
  template:
    metadata:
      labels:
        {{- include "k3s-server.labels" . | nindent 8 }}
    spec:
      containers:
        - name: generate-key
          image: headscale/headscale:stable-debug
          command: ["sh", "-c"]
          args:
            - |-
              headscale generate private-key > /tmp/noise_private.key
          volumeMounts:
            - name: tmp-storage
              mountPath: /tmp
            - name: headscale-configs
              mountPath: /etc/headscale
        - name: create-secret
          image: bitnami/kubectl:latest
          command: ["sh", "-c"]
          args:
            - |
              kubectl patch -n {{ .Release.Namespace }} secret "headscale-{{ include "k3s-server.fullname" . }}" --type='json' -p="[{\"op\": \"replace\", \"path\": \"/data/noise_private.key\", \"value\": \"$(base64 /tmp/noise_private.key)\"}]"
            - name: headscale-configs
              mountPath: /etc/headscale
            - name: tmp-storage
              mountPath: /tmp
      volumes:
        - name: tmp-storage
          emptyDir: {}
        - name: headscale-configs
          configMap:
            name: "headscale-{{ include "k3s-server.fullname" . }}"
        - name: headscale-configs-source
          secret:
            secretName: "headscale-{{ include "k3s-server.fullname" . }}"
      restartPolicy: OnFailure
      serviceAccount: "headscale-{{ include "k3s-server.fullname" . }}"
      serviceAccountName: "headscale-{{ include "k3s-server.fullname" . }}"