apiVersion: apps/v1
kind: Deployment
metadata:
  name: "headscale-{{ include "k3s-server.fullname" . }}"
  labels:
    app: "headscale-{{ include "k3s-server.fullname" . }}"
    {{- include "k3s-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: "headscale-{{ include "k3s-server.fullname" . }}"
      {{- include "k3s-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: "headscale-{{ include "k3s-server.fullname" . }}"
        {{- include "k3s-server.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "k3s-server.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          args:
            - 'serve'
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: headscale/headscale:stable
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /etc/headscale
              name: configs
            - mountPath: /etc/headscale_secret
              name: secret
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      initContainers:
        - name: wait-check-config
          command: ["sh", "-c"]
          args:
            - |-
              until headscale configtest; do
                echo "wait 'headscale configtest'"
                sleep 2
              done
          image: headscale/headscale:stable-debub
          volumeMounts:
            - mountPath: /etc/headscale
              name: configs
            - mountPath: /etc/headscale_secret
              name: secret
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: configs
          configMap:
            name: "headscale-{{ include "k3s-server.fullname" . }}"
        - name: secret
          secret:
            secretName: "headscale-{{ include "k3s-server.fullname" . }}"
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
