apiVersion: v1
kind: ServiceAccount
metadata:
  name: "headscale-{{ include "k3s-server.fullname" . }}"
  labels:
    {{- include "k3s-server.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k3s-server.fullname" . }}-secret-manager
  labels:
    {{- include "k3s-server.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "k3s-server.fullname" . }}-secret-manager-binding
  labels:
    {{- include "k3s-server.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "k3s-server.fullname" . }}-secret-manager
subjects:
  - kind: ServiceAccount
    name: "headscale-{{ include "k3s-server.fullname" . }}"
    namespace: {{ .Release.Namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "k3s-server.fullname" . }}-post-start-job"
  labels:
    {{- include "k3s-server.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  ttlSecondsAfterFinished: 10
  template:
    metadata:
      labels:
        {{- include "k3s-server.labels" . | nindent 8 }}
    spec:
      containers:
        - name: generate-key
          image: headscale/headscale:stable-debug
          command: ["sh", "-c"]
          args:
            - |-
              headscale generate private-key > /tmp/noise_private.key
          volumeMounts:
            - name: tmp-storage
              mountPath: /tmp
            - name: headscale-configs
              mountPath: /etc/headscale
        - name: create-secret-noise-private
          image: bitnami/kubectl:latest
          command: ["sh", "-c"]
          args:
            - |
              kubectl create -n {{ .Release.Namespace }} secret generic "headscale-noise-private-{{ include "k3s-server.fullname" . }}" --from-file=noise_private.key=/tmp/noise_private.key --dry-run=client -o yaml | kubectl apply -f -
          volumeMounts:
            - name: headscale-configs
              mountPath: /etc/headscale
            - name: tmp-storage
              mountPath: /tmp
        - name: create-database
          image: postgres:alpine
          command: ["sh", "-c"]
          args:
            - |
              export DSN=postgres://{{ $.Values.postgres.hs.username }}:{{ $.Values.postgres.hs.password }}@{{ $.Values.postgres.hs.hostname }}:{{ $.Values.postgres.hs.port }}?sslmode=disable
              psql $DSN -c "CREATE DATABASE {{ include "k3s-server.sanitizeNameHeadscale" . }};"
        - name: headscale-create-auth
          command: ["sh", "-c"]
          args:
            - |-
              until headscale configtest; do
                echo "wait 'headscale configtest'"
                sleep 5
              done
              headscale serve &
              until nc -zv 0.0.0.0:8080; do
                sleep 2
              done
              headscale users create {{ .Release.Name }}
              token=`headscale preauthkeys create --user {{ .Release.Name }} --reusable  --expiration 100y`
              echo -e "name=tailscale,joinKey=$token,controlServerURL=http://headscale.{{ $.Values.domain }}" > /tmp/headscale_auth_file
          image: headscale/headscale:stable-debug
          volumeMounts:
            - name: headscale-configs
              mountPath: /etc/headscale
            - name: tmp-storage
              mountPath: /tmp
            - name: headscale-noise-private
              mountPath: /etc/headscale_secret
        - name: create-secret-auth-file
          image: bitnami/kubectl:latest
          command: ["sh", "-c"]
          args:
            - |
              kubectl create -n {{ .Release.Namespace }} secret generic "headscale-auth-file-{{ include "k3s-server.fullname" . }}" --from-file=headscale_auth_file=/tmp/headscale_auth_file --dry-run=client -o yaml | kubectl apply -f -
          volumeMounts:
            - name: headscale-configs
              mountPath: /etc/headscale
            - name: tmp-storage
              mountPath: /tmp
      volumes:
        - name: tmp-storage
          emptyDir: {}
        - name: headscale-configs
          configMap:
            name: "headscale-{{ include "k3s-server.fullname" . }}"
        - name: headscale-noise-private
          secret:
            secretName: "headscale-noise-private-{{ include "k3s-server.fullname" . }}"
        - name: headscale-auth-file
          secret:
            secretName: "headscale-auth-file-{{ include "k3s-server.fullname" . }}"
      restartPolicy: OnFailure
      serviceAccount: "headscale-{{ include "k3s-server.fullname" . }}"
      serviceAccountName: "headscale-{{ include "k3s-server.fullname" . }}"