apiVersion: v1
stringData:
  noise_private.key: ""
kind: Secret
type: Opaque
metadata:
  name: "headscale-noise-private-{{ include "k3s-server.fullname" . }}"
  labels:
    {{- include "k3s-server.labels" . | nindent 4 }}
---
apiVersion: v1
stringData:
  headscale_auth_file: ""
kind: Secret
type: Opaque
metadata:
  name: "headscale-auth-file-{{ include "k3s-server.fullname" . }}"
  labels:
    {{- include "k3s-server.labels" . | nindent 4 }}
---
apiVersion: v1
stringData:
  token: ""
kind: Secret
type: Opaque
metadata:
  name: "token-{{ include "k3s-server.fullname" . }}"
  labels:
    {{- include "k3s-server.labels" . | nindent 4 }}