apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k3s-server.fullname" . }}
  labels:
    app: "{{ include "k3s-server.fullname" . }}"
    {{- include "k3s-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: "{{ include "k3s-server.fullname" . }}"
      {{- include "k3s-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: "{{ include "k3s-server.fullname" . }}"
        {{- include "k3s-server.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "k3s-server.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - args:
            - tailscaled
          image: tailscale/tailscale
          name: tailscaled
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          volumeMounts:
            - mountPath: /dev/net/tun
              name: dev-tun
            - mountPath: /var/run/tailscale
              name: tailscale-socket
            - mountPath: /var/lib/tailscale
              name: tailscale-data
            - mountPath: /var/lib
              name: var-lib
        - name: {{ .Chart.Name }}
          command:
            - k3s
            - server
          args:
            - '--disable-agent'
            - '--node-taint=CriticalAddonsOnly=true:NoExecute'
            - '--https-listen-port={{ $.Values.service.port }}'
            - '--tls-san=api.{{ $.Values.domain }}'
            - '--disable=servicelb'
            - '--disable=traefik'
            - '--disable=local-storage'
            - '--disable=metrics-server'
            - '--vpn-auth-file=/var/run/headscale/headscale_auth_file'
          {{- with .Values.args }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: PATH
              value: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/bin/aux:/tailscale-binary"
            - name: K3S_DATASTORE_ENDPOINT
              value: postgres://{{ $.Values.postgres.k3s.username }}:{{ $.Values.postgres.k3s.password }}@{{ $.Values.postgres.k3s.hostname }}:{{ $.Values.postgres.k3s.port }}/{{ include "k3s-server.sanitizeName" . }}?sslmode=disable
            - name: K3S_TOKEN
              value: {{ $.Values.token }}
          {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: k3s
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /tailscale-binary
              name: tailscale-binary
            - mountPath: /var/run/tailscale
              name: tailscale-socket
            - mountPath: /var/lib/tailscale
              name: tailscale-data
            - mountPath: /var/run/headscale
              name: headscale-secret
            - mountPath: /dev/net/tun
              name: dev-tun
            - mountPath: /var/lib
              name: var-lib
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      initContainers:
        - args:
            - '-c'
            - cp /usr/local/bin/tailscale /tailscale-binary/tailscale
          command:
            - sh
          image: tailscale/tailscale
          name: tailscale-binary
          volumeMounts:
            - mountPath: /tailscale-binary
              name: tailscale-binary
        - args:
            - |
              until grep -q "joinKey" /var/run/headscale/headscale_auth_file 2>/dev/null; do
                echo "wait /var/run/headscale/headscale_auth_file"
                sleep 2
              done
              until nc -zv headscale-{{ include "k3s-server.fullname" . }}:8080; do
                echo "wait headscale service is up"
                sleep 2
              done
          command: ["sh", "-c"]
          image: tailscale/tailscale
          name: check-headscale-auth-file
          volumeMounts:
            - mountPath: /var/run/headscale
              name: headscale-secret
      volumes:
        - name: headscale-secret
          secret:
            secretName: "headscale-auth-file-{{ include "k3s-server.fullname" . }}"
        - hostPath:
            path: /dev/net/tun
            type: CharDevice
          name: dev-tun
        - emptyDir: {}
          name: tailscale-binary
        - emptyDir: {}
          name: tailscale-socket
        - emptyDir: {}
          name: tailscale-data
        - emptyDir: {}
          name: headscale-socket
        - emptyDir: {}
          name: var-lib
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
