apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k3s-server.fullname" . }}
  labels:
    app: "{{ include "k3s-server.fullname" . }}"
    {{- include "k3s-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: "{{ include "k3s-server.fullname" . }}"
      {{- include "k3s-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: "{{ include "k3s-server.fullname" . }}"
        {{- include "k3s-server.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "k3s-server.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          command:
            - k3s
            - server
          args:
            - '--disable-agent'
            - '--node-taint=CriticalAddonsOnly=true:NoExecute'
            - '--https-listen-port={{ $.Values.service.port }}'
            - '--tls-san=api.{{ $.Values.domain }}'
            - '--disable=servicelb'
            - '--disable=traefik'
            - '--disable=local-storage'
            - '--disable=metrics-server'
          {{- with .Values.args }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: K3S_DATASTORE_ENDPOINT
              value: postgres://{{ $.Values.postgres.k3s.username }}:{{ $.Values.postgres.k3s.password }}@{{ $.Values.postgres.k3s.hostname }}:{{ $.Values.postgres.k3s.port }}/{{ include "k3s-server.sanitizeName" . }}?sslmode=disable
            - name: K3S_TOKEN
              value: {{ $.Values.token }}
          {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: k3s
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      initContainers:
        - name: wait-check-config
          command: ["sh", "-c"]
          args:
            - |-
              until headscale configtest; do
                echo "wait 'headscale configtest'"
                sleep 2
              done
          image: headscale/headscale:stable-debug
          volumeMounts:
            - mountPath: /etc/headscale
              name: headscale-configs
            - mountPath: /etc/headscale_secret
              name: headscale-secret
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: headscale-configs
          configMap:
            name: "headscale-{{ include "k3s-server.fullname" . }}"
        - name: headscale-secret
          secret:
            secretName: "headscale-{{ include "k3s-server.fullname" . }}"
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
