apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "k3s-server.fullname" . }}-delete-db"
  labels:
    {{- include "k3s-server.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-delete-policy": "hook-succeeded"
spec:
  template:
    metadata:
      labels:
        {{- include "k3s-server.labels" . | nindent 8 }}
    spec:
      containers:
        - name: drop-database-k3s
          image: {{ $.Values.k3s.database.image }}
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c"]
          args:
            - |
              export DSN='{{ $.Values.k3s.database.type }}://{{ $.Values.k3s.database.username }}:{{ $.Values.k3s.database.password }}@{{ $.Values.k3s.database.hostname }}:{{ $.Values.k3s.database.port }}?{{ $.Values.k3s.database.query }}'
              {{ $.Values.k3s.database.cli }} $DSN -c "DROP DATABASE IF EXISTS {{ include "k3s-server.sanitizeName" . }};"
        - name: drop-database-hs
          image: postgres:alpine
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c"]
          args:
            - |
              export DSN='{{ $.Values.hs.database.type }}://{{ $.Values.hs.database.username }}:{{ $.Values.hs.database.password }}@{{ $.Values.hs.database.hostname }}:{{ $.Values.hs.database.port }}?{{ $.Values.hs.database.query }}'
              psql $DSN -c "DROP DATABASE IF EXISTS {{ include "k3s-server.sanitizeNameHeadscale" . }};"
      restartPolicy: Never
      serviceAccount: default
      serviceAccountName: default